### PR TITLE
Add RemoveDevice

### PR DESCRIPTION
**Pull request by yotabits**
Add RemoveDevice according to:
https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/doc/adapter-api.txt

### CODE REVIEW

**Comment by yotabits** [comment]
@ukBaz 
I'm not sure about this one, as is, if used with a device object from the python api it should be called as following:
`adapter.remove_device(my_device.remote_device_obj)`

**Comment by yotabits** [comment]
@ukBaz may I have some feed back please :) 
https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/doc/adapter-api.txt#n40

**Comment by ukBaz** [comment]
Hi @yotabits, I need to run this on some real hardware before I give feedback on this. I hope to get to this later in the week.

**Comment by ukBaz** [comment]
Some notes on how I tested this PR.

In `bluetoothctl` I had a device:
```
[bluetooth]# devices
Device F1:55:90:65:29:DC BBC micro:bit [zetuz]
```

I started the python command line and used the new function to remove it.
``` python
$ python3
Python 3.5.3 (default, Sep 27 2018, 17:25:39)
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from bluezero import adapter
>>> dongle = adapter.Adapter()
>>> dongle.remove_device('/org/bluez/hci0/dev_F1_55_90_65_29_DC')
```
It felt a little bit awkward having to find out that dbus object path. So I did it again after creating a Bluezero Device of the BlueZ device:

```python
ubit = device.Device(adapter_addr='02:00:AA:48:25:29', device_addr='F1:55:90:65:29:DC')
>>> dongle.remove_device(ubit.remote_device_path)
```
As a test I recreated the device and this time connected to it. I then, after disconnecting, removed the device. I then tried to reconnect at the Bluezero device existed although the BlueZ one didn't:
``` python
>>> ubit.connect()
>>> ubit.disconnect()
>>> dongle.remove_device(ubit.remote_device_path)
>>> ubit.connect()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/my-workspace/python-bluezero/bluezero/device.py", line 257, in connect
    self.remote_device_methods.Connect()
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownObject: Method "Connect" with signature "" on interface "org.bluez.Device1" doesn't exist
```
This gave a very unhelpful error message. I did an experiment to see what it would look like if I put the remove method inside of the `Device` class. Something like:

```python
    def remove(self):
        """
        Remove device from adapter and clear pairing
        info if it exists
        """
        adapter_object = self.bus.get_object(constants.BLUEZ_SERVICE_NAME, self.adapter)
        adapter_methods = dbus.Interface(adapter_object, constants.ADAPTER_INTERFACE)
        adapter_methods.RemoveDevice(self.remote_device_path)
        del self

```
I think this is more readable.
```python
$ python3Python 3.5.3 (default, Sep 27 2018, 17:25:39)
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from bluezero import device
>>> ubit = device.Device(adapter_addr='02:00:AA:48:25:29', device_addr='F1:55:90:65:29:DC')
>>> ubit.remove()
```
Although it still have the problem that the `ubit` instance still existed.

This got me to thinking that creating a `__del__` method might be the right thing to do.
```python
    def __del__(self):
        """
        Remove device from adapter and clear pairing
        info if it exists
        """
        adapter_object = self.bus.get_object(constants.BLUEZ_SERVICE_NAME, self.adapter)
        adapter_methods = dbus.Interface(adapter_object, constants.ADAPTER_INTERFACE)
        adapter_methods.RemoveDevice(self.remote_device_path)
```
This seemed to handle things nicely:
```python
>>> from bluezero import device>>> ubit = device.Device(adapter_addr='02:00:AA:48:25:29', device_addr='F1:55:90:65:29:DC')
>>> ubit.connect()
>>> del ubit
>>> ubit.disconnect()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'ubit' is not defined
```

What are your thoughts on this?

**Comment by uSpike** [comment]
Hi, just passing by.  I think using `__del__` is the wrong path. 

https://docs.python.org/3/reference/datamodel.html#object.__del__
> Called when the instance is about to be destroyed. This is also called a finalizer or (improperly) a destructor. 

AFAIK you don't want the device to be removed when the object is garbage collected, which may be any time or not at all.

> It is not guaranteed that __del__() methods are called for objects that still exist when the interpreter exits.

I think if you `device.remove()` and then try to do things with the object, you're just asking for trouble, but it's up to you.

**Pull request closed without merging**
