### PR TITLE
Add miscellaneous functionalities

### PR DESCRIPTION
**Pull request by yotabits**
**Add uuid attribute to Adapter** 
    According to:
    https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/doc/adapter-api.txt
    Adapter1 interface has for attribute a list of UUIDs corresponding to the
    physical device.
    We here made this list available to the Adapter python class.

**Added object inheritance** 
    As we are running python 2.7 we need
    to inherit from object to take advantage
    of @property decorators.

**Add method to Pair device** 
    According to
    https://git.kernel.org/pubs/scm/bluetooth/bluez.git/tree/doc/device-api.txt
    Device dbus object provides a method to pair.

**Add a method to get Devices assigned to an Adapter** 
    This is necessary when we want to filter which device we will work with.
    Another way would have been to use the device filter of an adapter
    for more details:
    https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/doc/adapter-api.txt

**Add asynchronous scan** 
    Now Adapter can perform safe asynchronous scans.

### CODE REVIEW

**Comment by yotabits** [comment]
I'm not sure this item is necessary:
```
Add a method to get Devices assigned to an Adapter
This is necessary when we want to filter which device we will work with.
Another way would have been to use the device filter of an adapter
for more details:
https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/doc/adapter-api.txt
```

Please give me your feed back :)

**Comment by yotabits** [comment]
This PR might bring too many changes at once, if it's the case, please close it and let me pr item by item if necessary.

**Comment by ukBaz** [comment]
Thanks for the PR. It will be a few days before I can actually run this on hardware but I want to get some feedback to you in a timely manner so here are my initial thoughts on what you have done.

1) Adapter: UUIDs property
This seems a straightforward addition.

2) object inheritance for 2.7
According to https://pythonclock.org/ we are only 8 months away from Python 2.7 the end of maintenance. I know it will continue to work beyond that but I would like to be discouraging 2.7 use, not encouraging.
Having said that, this is a minor change and I would merge if you are sure you are not about to move from 2.7.

3) Pairing
To implement the methodology seems straight forward. The tricky bit with pairing is the agent to handle entering the pin or whatever.
I would be interested to hear how this is working in practice. How are you getting users to complete the pairing process?
If we add pairing it would probably make sense to do [cancel_pairing](https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/doc/device-api.txt?h=5.43#n111) also

4) method to get Devices assigned to an Adapter
I am not sure I understand the purpose of this. Where and how would you use this information?
It seems to mix a couple of functions together. I suspect this is to do with the asynchronous scan. When a device is discovered you want to create a Bluezero Device object. If that is the case, then an update to [`_properties_changed`](https://github.com/ukBaz/python-bluezero/blob/master/bluezero/adapter.py#L234) method is required. You would also need to destroy the Device object when a device is removed by the Bluetooth daemon.
If you want to just pick one device to connect to from an already discovered list, then I don't think you need to create all of the Device objects. Query GetManagedObjects to find the device of interest.
There is a mock of what  GetManagedObjects returns at:
https://github.com/campug/bzero_kata/blob/master/mock_pydbus.py
I suspect you would create a function in dbus_tools that returns a device list filtered by service uuid.
Not sure I have explained that well but if you let me know what you are trying to do we can iterate on this.

5) asynchronous scan
Bluezero has strange relationship with running asynchronously. This library is targeted at people getting started and for most users async is a new concept to them. However for many things on Bluetooth async is the way it works. This is partly why we talk about complexity levels in the [overview](https://bluezero.readthedocs.io/en/stable/overview.html) of this library.
Would it be possible for you to create an example of using this function?
I would also suggest we go with the name `start_discovery` rather than `nearby_discovery_async`.

Maybe if you split the PR so the more straight forward bits can be merged while we iterate on some of the more complex ones?

**Comment by yotabits** [comment]
@ukBaz Thank you for your quick reply. I will create PR's for obvious stuff and let's discuss the rest later :+1:

**Comment by yotabits** [comment]
1. is solved by #217 
3. is solved by #218 

2. I'm using this API in a ROS environment, I might not move away from 2.7 before a while :crying_cat_face:

**Comment by ukBaz** [comment]
This is being covered by other smaller PR's so I'm closing this one

**Pull request closed without merging**
