### PR TITLE
add devices property to adapters

### PR DESCRIPTION
**Pull request by xloem**
This provides a way to enumerate devices that have already been found, even before launch of the program.

### CODE REVIEW

**Comment by ukBaz** [comment]
I prefer to avoid `for` loops with `continue` in them if at all possible. Iterating around the managed object is maybe more efficient like this:
```python
known_devices = []
mng_objs = dbus_tools.get_managed_objects()
for path in mng_objs:
    if path.startswith(self.path):
        address = mng_objs[path].get(constants.DEVICE_INTERFACE, {}).get('Address')
        if address:
            known_devices.append(address)
```

I like this idea of getting a list of the known devices. A couple of things to think about before I merge.

Should this be in devices.py and be a class method?
Should it return a Bluezero `device` object rather than a list of addresses? That is what the `_interfaces_added` does.

**Comment by ukBaz** [comment]
@xloem , I've been thinking about this a little bit more. Something that would be helpful for me is if you could give an example of how this would be used. This might help me answer the two questions I raised above.

If you wanted to connect to a device by name then you could do:
```python
from bluezero import device

def find_by_name(target_name):
    for bt_dev in known_devices():
        if bt_dev.name == target_name:
            retrun bt_dev

target_dev = find_by_name('BBC micro:bit [zuvig]')
target_dev.connect()
```

If the device look up returns the address then it becomes more involved.

Do you ever want just a list of addresses? This made me wonder if the device look up should be a generator.

One idea for use of a list would be to decide if the device address is already known. If not in list, then do a discovery. e.g.
```python
if not 'E5:10:5E:37:11:2D' in known_addersses():
    adapter.nearby_discovery()
```

Be interested to hear your thoughts on how you think this method/function will be used.

**Comment by xloem** [comment]
Hey, here's where I come from with this:
- i'm working with a device where each model has a different name (the name includes the serial number).  so i'm matching based on the first half of the mac address, to detect that the device may be supported.
- i'd like the user to be able to connect to multiple devices of this type.
- i'd like it to be possible to show the user a list of nearby devices, so they can diagnose connection issues some.

I like the idea of using devices instead of just addresses, too.  I was just trying to copy the existing patterns of the code as I saw them.  It would even be nice to maintain a set of device objects associated with each interface.  The objects could have initialization code moved out of the constructor if eventually needed to make that more lightweight.

I've also since discovered https://github.com/labapart/gattlib which is presently used by pybluez; it might make sense to trend all these libraries towards being similar to each other to make things easier on users.

I'll update my PR as you proposed in your first comment.

**Comment by xloem** [comment]
Your proposed code iterates all devices, rather than just the ones associated with a single adapter.  I think it would need to return a whole Device object, so the user doesn't need to find the adapter that's within range.  I'm a little taxed for time here, and not sure of your preferred solution, so I'm just removing the `continue` parts from my current code for now.

**Comment by xloem** [comment]
I implemented some of your ideas.  There's also `device.list_adapters` which could be made similar if we pick an interface norm.

**Comment by ukBaz** [comment]
Thanks for spending the time on this PR. Bluezero has evolved over the last five years and there are a number of things I would like to refactor (including `list_adapters`). The focus at the moment is removing the dependency on aioblescan and implementing a better testing strategy. If there could be better test coverage then refactoring would be easier.

You are correct when you say there are a number of other Bluetooth libraries. I've tried to keep a list of many of them at https://github.com/ukBaz/python-bluezero/wiki. There is also the [pydbus library ](https://pypi.org/project/pydbus/) which is great for building [clients ](https://gist.github.com/ukBaz/2ca25e5c397d93626a44d6229d763ab8 )or [observers](https://gist.github.com/ukBaz/488258e93b02366861e3c8c881191081). However, I think it is testing strategies that hold most (if not all of them back). They reach a certain size and it becomes too difficult for people to know they are not making non-breaking changes. The goal of Bluezero has always been to help people get started with Bluetooth rather than be the ultimate Python Bluetooth library.

Anyway, back to this PR. Just a couple of minor tweaks and I think we will be good. 

- Can we remove the `devices` method from `adapter.py` as it is replaced by `known` in `device.py`?
- After seeing the implementation of `known`, I am thinking that passing in the adapter object would make sense. Thoughts?

**Comment by xloem** [comment]
There are a lot of solutions to the extra bus calls in `known`.  Since you mentioned `list_adapters` being outdated and it has parallel behavior, I removed `devices` and moved those bus calls into a new `available` method on Adapter.  What do you think of this?

I might not have the time to take this PR to completion; we'll see.

**Comment by ukBaz** [comment]
OK, this is turning in to a bit of a monster!!!  I think this has been a really useful PR and has helped clarify some things for me.

I've finished my update to remove aioblescan from the dependency for Bluezero so I might have time to look at this now. I like the idea of having an `available` function in `adapter` and `device` that list known adapters and devices returning a generator of those objects. I will also leave `list_adapters` for now but mark it as deprecated.

If you are OK with that then I'll close this PR and create a fresh one.

**Comment by xloem** [comment]
sure

**Comment by ukBaz** [comment]
Thanks for all your work on this PR. Very much appreciated

**Comment by ukBaz** [comment]
Working nicely! 
image

**Comment by xloem** [comment]
Thanks for merging this.  I'm thinking of ease of use, and imagining scanning might be a lot easier if these functions took a flag to initiate discovery.  Discovery would probably have to automatically terminate after a timeout if the yield call didn't come back.

I'm also trying out running a system-wide pump loop in a thread in my client code locally, which simplifies interfaces.

**Comment by xloem** [comment]
> You are correct when you say there are a number of other Bluetooth libraries. I've tried to keep a list of many of them at https://github.com/ukBaz/python-bluezero/wiki. There is also the [pydbus library ](https://pypi.org/project/pydbus/) which is great for building [clients ](https://gist.github.com/ukBaz/2ca25e5c397d93626a44d6229d763ab8)or [observers](https://gist.github.com/ukBaz/488258e93b02366861e3c8c881191081). However, I think it is testing strategies that hold most (if not all of them back). They reach a certain size and it becomes too difficult for people to know they are not making non-breaking changes. The goal of Bluezero has always been to help people get started with Bluetooth rather than be the ultimate Python Bluetooth library.

Just to let you know, I've basically settled on bleak as a stable, cross-platform library that is easy to use.  I submitted an unpolished android backend to it.

I enjoyed working with you on your library, but in the end I wanted to support windows and macosx too.

**Comment by ukBaz** [comment]
Thanks for the update

**Pull request merged**
