### PR TITLE
Added Bluetooth media player

### PR DESCRIPTION
**Pull request by FahirahD**
Needed to play audio from my phone with a raspberry pi seems like it works really accurately with bluealsa-aplay and an external USB card, so i decided to give a shot and contribute at the same time since i want to use a python script. I made sure it was working correctly on my computer running on Debian.

### CODE REVIEW

**Comment by ukBaz** [comment]
Thanks @FahirahD for a very cool pull-request. My assumption is that this will need to be added to the list of level-100 files in https://github.com/ukBaz/python-bluezero/blob/master/docs/overview.rst

You have named the file `mediaPlayer.py` file with camelcase. I would have preferred all-lowercase name with an underscore. So `media_player.py` to be inline with PEP8 recommendation.
https://www.python.org/dev/peps/pep-0008/#package-and-module-names
I've not adhered to the rules rigidly, but I will probably change the name.

The biggest issue with me merging this is testing. Writing tests for this library is difficult, but maybe you could create a small example that would allow me to exercise this code if I connect my phone up to the Raspberry Pi. What do you think? Is that easy to do?

**Comment by FahirahD** [comment]
i think it is a good idea, it does not sound that hard, ill work on that , do you recommend any way of testing ? I thought about making a simple command line script that will allow to interact with it using the input. if i run into issues, ill let you know.

**Comment by ukBaz** [comment]
> do you recommend any way of testing ?

Something that is very straight forward to get up and running is normally the most useful to help build users confidence that they have the basic setup correct.
Maybe a little script that gets the track name, is shuffle on or off etc would be a good first step.

Previously I have had some issues with audio as I have documented at:
https://ukbaz.github.io/howto/Bluetooth_speakers.html
Did you experience this also?
I am assuming you are using this in Receiving Audio (Audio Sink - 0x110B) on the Raspberry Pi.

**Comment by ukBaz** [comment]
That last submit (https://github.com/ukBaz/python-bluezero/pull/256/commits/476cd6e5f5ae4f118e2d5cb07af0503afed2519b) would be better in a separate PR as it is a broader fix beyond the scope of adding the Bluetooth media player.

**Comment by ukBaz** [comment]
I've done a little test script of:
```python
from bluezero import mediaPlayer

mp = mediaPlayer.MediaPlayer('/org/bluez/hci0/dev_80_5A_04_13_95_EB/player0')

track_details = mp.track
for detail in track_details:
    print(f'{detail} : {track_details[detail]}')
```
Which gave me the following output:
```
$ python3 examples/track_details.py 
Title : Happy Birthday
TrackNumber : 0
NumberOfTracks : 0
Duration : 357000
Album : Hotter Than July
Item : /org/bluez/hci0/dev_80_5A_04_13_95_EB/player0/NowPlaying/item1
Artist : Stevie Wonder
```

Seems to work well. The only thing that feels slightly awkward is the parameter `player_addr`. Took me a while to workout what was required to be entered there. Would be good if it could take the address of the device (i.e: `80:5A:04:13:95:EB`) if that is possible to be consistent with the rest of the library.

**Comment by FahirahD** [comment]
> I've done a little test script of:
> 
> ```python
> from bluezero import mediaPlayer
> 
> mp = mediaPlayer.MediaPlayer('/org/bluez/hci0/dev_80_5A_04_13_95_EB/player0')
> 
> track_details = mp.track
> for detail in track_details:
>     print(f'{detail} : {track_details[detail]}')
> ```
> 
> Which gave me the following output:
> 
> ```
> $ python3 examples/track_details.py 
> Title : Happy Birthday
> TrackNumber : 0
> NumberOfTracks : 0
> Duration : 357000
> Album : Hotter Than July
> Item : /org/bluez/hci0/dev_80_5A_04_13_95_EB/player0/NowPlaying/item1
> Artist : Stevie Wonder
> ```
> 
> Seems to work well. The only thing that feels slightly awkward is the parameter `player_addr`. Took me a while to workout what was required to be entered there. Would be good if it could take the address of the device (i.e: `80:5A:04:13:95:EB`) if that is possible to be consistent with the rest of the library.

Sorry, i was figuring that out it should work now with the device mac address, i also did a little test script but i don't know if its still relevant

**Comment by ukBaz** [comment]
This is fun functionality to add to Bluezero so I have gone ahead and merged it because this functionality is independent from other parts of Bluezero so there seems a low risk of it breaking something else.
I will go ahead and change the file name. I'll also add it into the documentation and put an example script in the examples to help people get started.
Thanks

**Pull request merged**
