### PR TITLE
Add asynchronous scan

### PR DESCRIPTION
**Pull request by yotabits**
Now Adapter can perform safe asynchronous scans.

### CODE REVIEW

**Comment by ukBaz** [comment]
I am in two minds about this PR.  Part of me thinks that I should just merge it as the method works. Part of me thinks that I should not because there is not the supporting functionality. By supporting functionality I am referring to `on_discovered_device` in `_properties_changed`. There is also not an example of how to run this.
My concern is that it is easy for people to get in a mess with this.

Have you been using this on your project @yotabits ?

**Comment by yotabits** [comment]
For my project, I need to have asynchronous scanning as I automatically pair with a device having a given mac address or following a specific name pattern.

As far as I can understand the call back made in properties changes are only here to handle changes in adapter [dbus properties](https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/doc/adapter-api.txt#n192) which does not give any information about the devices found during the scanning

**Comment by ukBaz** [comment]
Apologies. You are correct, it is not the `PropertiesChanged` signal that you need to subscribe to. For new devices it is `InterfacesAdded`.

This is setup in the `adapter.py` file:
https://github.com/ukBaz/python-bluezero/blob/030ad711efeedb7186d667ffa5e15a1492d9e6bc/bluezero/adapter.py#L95-L97

But points to a callback in `dbus_tools.py`:
https://github.com/ukBaz/python-bluezero/blob/030ad711efeedb7186d667ffa5e15a1492d9e6bc/bluezero/dbus_tools.py#L50-L58

There does not seem to be anything for `InterfacesRemoved` currently.

I think you need this functionality so that you know when you have found the device you are looking for and can stop the scan.

**Comment by ukBaz** [comment]
Hi @yotabits,

I have done some experimentation this evening to better understand the options for this. Please take a look at this commit: https://github.com/ukBaz/python-bluezero/commit/cee8981af21851cd9bedea193ebcd63bf9f861a7

This is unlikely to get merged into master as I would like to do some more thinking about it. For example,
I think `_interfaces_added` should maybe do more work to present information better to the `on_device_found` callback.

I would be interested in your feedback.

**Comment by ukBaz** [comment]
This PR never got merged but I believe the functionality is now in the the library through other development so I'll go ahead and close this

**Pull request closed without merging**
